import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../data/cocktail_repository.dart';
import '../../../services/gemini_service.dart';

/// Dialog to generate and share a WhatsApp offer message with optional PDF attachment.
///
/// The middle "cocktail commentary" part is generated by Gemini.
/// The PDF is generated via [generatePdfBytes] callback and shared using
/// the platform's native share sheet (Printing.sharePdf), which allows
/// users to attach it directly in WhatsApp on mobile/desktop.
class OfferShareDialog extends StatefulWidget {
  const OfferShareDialog({
    super.key,
    required this.clientName,
    required this.editorName,
    required this.selectedCocktails,
    required this.generatePdfBytes,
    required this.pdfFilename,
  });

  final String clientName;
  final String editorName;
  final List<String> selectedCocktails;

  /// Callback that generates and returns the PDF bytes for the offer.
  final Future<Uint8List> Function() generatePdfBytes;

  /// The filename used when sharing the PDF (e.g. "angebot_foo_20260316.pdf").
  final String pdfFilename;

  @override
  State<OfferShareDialog> createState() => _OfferShareDialogState();
}

class _OfferShareDialogState extends State<OfferShareDialog> {
  late final TextEditingController _messageCtrl;
  bool _loading = true;
  String? _error;
  bool _pdfSharing = false;

  /// Mutable copy of selectedCocktails — updated by swap dropdowns.
  late List<String> _currentCocktails;

  /// All cocktail names from the repository, used to populate dropdowns.
  List<String> _allCocktails = [];

  /// True when the user has swapped a cocktail but Gemini hasn't been re-called yet.
  bool _isDirty = false;

  @override
  void initState() {
    super.initState();
    _currentCocktails = List.from(widget.selectedCocktails);
    _messageCtrl = TextEditingController();
    _generate();
  }

  @override
  void dispose() {
    _messageCtrl.dispose();
    super.dispose();
  }

  String get _clientFirstName {
    final name = widget.clientName.trim();
    if (name.isEmpty) return name;
    return name.split(' ').first;
  }

  String get _editorFirstName {
    final name = widget.editorName.trim();
    if (name.isEmpty) return name;
    return name.split(' ').first;
  }

  Future<void> _generate() async {
    setState(() {
      _loading = true;
      _error = null;
      _isDirty = false;
    });

    try {
      // Load all available cocktail names from the repository for context
      if (_allCocktails.isEmpty) {
        try {
          final data = await cocktailRepository.load();
          _allCocktails = data.recipes.map((r) => r.name).toList();
        } catch (_) {
          // Fallback: continue without full recipe list
        }
      }

      String? middlePart;
      if (geminiService.isConfigured) {
        middlePart = await geminiService.generateOfferShareMessage(
          originalCocktails: widget.selectedCocktails,
          selectedCocktails: _currentCocktails,
          allAvailableCocktails: _allCocktails,
        );
      }

      // Assemble the full message
      final message = _buildMessage(middlePart);
      if (mounted) {
        setState(() {
          _messageCtrl.text = message;
          _loading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = 'offer.share_generate_error'.tr();
          _loading = false;
        });
      }
    }
  }

  String _buildMessage(String? geminiMiddle) {
    final clientFirst = _clientFirstName.isNotEmpty
        ? _clientFirstName
        : widget.clientName;
    final editorFirst = _editorFirstName.isNotEmpty
        ? _editorFirstName
        : widget.editorName;

    final middle = (geminiMiddle != null && geminiMiddle.isNotEmpty)
        ? geminiMiddle
        : widget.selectedCocktails.isNotEmpty
            ? 'Wir haben uns die Auswahl angeschaut – ${widget.selectedCocktails.join(', ')} ist eine schöne Kombination!'
            : 'Wir haben dein Angebot basierend auf deiner Auswahl zusammengestellt.';

    return '''Hallo $clientFirst,

hier ist $editorFirst von Black Lodge! 😊

Wir haben dir das Angebot basierend auf deiner Auswahl erstellt. Hier noch ein kurzer Input von uns zum Mix:

$middle

Das Angebot ist ab heute 14 Tage gültig. Wenn das für dich so passt, gib uns kurz Bescheid, dann senden wir dir das Auftragsdokument für die Anzahlung zu.

Bei Fragen können wir gerne unter der Woche mal telefonieren.

Schönen Tag noch! 😊

Beste Grüße,
$editorFirst''';
  }

  void _swapCocktail(int index, String newValue) {
    setState(() {
      _currentCocktails[index] = newValue;
      _isDirty = true;
    });
  }

  Widget _buildSwapSection(ColorScheme colorScheme) {
    if (_allCocktails.isEmpty || _currentCocktails.isEmpty) return const SizedBox.shrink();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'offer.share_cocktail_selection'.tr(),
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w600,
            color: colorScheme.onSurfaceVariant,
          ),
        ),
        const SizedBox(height: 8),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            for (int i = 0; i < _currentCocktails.length; i++)
              _CocktailDropdown(
                value: _currentCocktails[i],
                allCocktails: _allCocktails,
                isChanged: _currentCocktails[i] != widget.selectedCocktails[i],
                onChanged: (val) {
                  if (val != null) _swapCocktail(i, val);
                },
              ),
          ],
        ),
        const SizedBox(height: 16),
      ],
    );
  }

  Future<void> _copyToClipboard() async {
    await Clipboard.setData(ClipboardData(text: _messageCtrl.text));
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('offer.share_copied'.tr())),
      );
    }
  }

  Future<void> _openWhatsApp() async {
    final encoded = Uri.encodeComponent(_messageCtrl.text);
    // Works on web and mobile
    final webUrl = Uri.parse('https://api.whatsapp.com/send?text=$encoded');
    if (await canLaunchUrl(webUrl)) {
      await launchUrl(webUrl, mode: LaunchMode.externalApplication);
    } else {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('offer.share_whatsapp_unavailable'.tr())),
        );
      }
    }
  }

  /// Share PDF via native share sheet (mobile: WhatsApp/etc., desktop: download).
  /// Copies the message text to clipboard first so the user can paste it in WhatsApp.
  Future<void> _sharePdf() async {
    setState(() => _pdfSharing = true);
    try {
      // Copy message text to clipboard so user can paste it alongside the PDF
      await Clipboard.setData(ClipboardData(text: _messageCtrl.text));

      final bytes = await widget.generatePdfBytes();

      // Trigger native share sheet / download
      await Printing.sharePdf(bytes: bytes, filename: widget.pdfFilename);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('offer.share_pdf_hint'.tr())),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('offer.share_pdf_error'.tr())),
        );
      }
    } finally {
      if (mounted) setState(() => _pdfSharing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Dialog(
      insetPadding: const EdgeInsets.all(24),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: Container(
        width: 700,
        constraints: const BoxConstraints(maxHeight: 700),
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            Row(
              children: [
                Icon(Icons.share, color: colorScheme.primary),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'offer.share_title'.tr(),
                    style: const TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                IconButton(
                  onPressed: () => Navigator.of(context).pop(),
                  icon: const Icon(Icons.close),
                ),
              ],
            ),
            const Divider(height: 24),

            // Content
            Flexible(
              child: _loading
                  ? Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const CircularProgressIndicator(),
                          const SizedBox(height: 16),
                          Text('offer.share_generating'.tr()),
                        ],
                      ),
                    )
                  : _error != null
                  ? Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            Icons.error_outline,
                            size: 48,
                            color: colorScheme.error,
                          ),
                          const SizedBox(height: 12),
                          Text(_error!),
                          const SizedBox(height: 16),
                          FilledButton(
                            onPressed: _generate,
                            child: Text('common.retry'.tr()),
                          ),
                        ],
                      ),
                    )
                  : SingleChildScrollView(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _buildSwapSection(colorScheme),
                          // Regenerate button above the text field
                          Row(
                            mainAxisAlignment: MainAxisAlignment.end,
                            children: [
                              if (_isDirty)
                                FilledButton.tonalIcon(
                                  onPressed: _pdfSharing ? null : _generate,
                                  icon: const Icon(Icons.auto_awesome, size: 18),
                                  label: Text('offer.share_regenerate_hint'.tr()),
                                  style: FilledButton.styleFrom(
                                    backgroundColor: colorScheme.tertiaryContainer,
                                    foregroundColor: colorScheme.onTertiaryContainer,
                                  ),
                                )
                              else
                                IconButton.outlined(
                                  onPressed: _pdfSharing ? null : _generate,
                                  icon: const Icon(Icons.refresh, size: 20),
                                  tooltip: 'offer.share_regenerate'.tr(),
                                ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          TextField(
                            controller: _messageCtrl,
                            maxLines: null,
                            decoration: InputDecoration(
                              border: const OutlineInputBorder(),
                              labelText: 'offer.share_message_label'.tr(),
                            ),
                            style: const TextStyle(fontSize: 14, height: 1.5),
                          ),
                        ],
                      ),
                    ),
            ),

            const SizedBox(height: 16),

            // Actions
            if (!_loading && _error == null) ...[
              // ── Hint ─────────────────────────────────────────────────────
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                decoration: BoxDecoration(
                  color: colorScheme.secondaryContainer.withValues(alpha: 0.5),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  children: [
                    Icon(Icons.info_outline, size: 16, color: colorScheme.onSecondaryContainer),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'offer.share_pdf_tip'.tr(),
                        style: TextStyle(
                          fontSize: 12,
                          color: colorScheme.onSecondaryContainer,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 12),
              // ── Buttons ───────────────────────────────────────────────────
              Wrap(
                spacing: 8,
                runSpacing: 8,
                alignment: WrapAlignment.end,
                children: [
                  // Copy text
                  OutlinedButton.icon(
                    onPressed: _loading || _pdfSharing ? null : _copyToClipboard,
                    icon: const Icon(Icons.copy, size: 18),
                    label: Text('offer.share_copy'.tr()),
                  ),
                  // WhatsApp text only
                  OutlinedButton.icon(
                    onPressed: _loading || _pdfSharing ? null : _openWhatsApp,
                    icon: const Icon(Icons.chat, size: 18),
                    label: Text('offer.share_whatsapp'.tr()),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: const Color(0xFF25D366),
                      side: const BorderSide(color: Color(0xFF25D366)),
                    ),
                  ),
                  // Share PDF (copy text + native share sheet)
                  FilledButton.icon(
                    onPressed: _loading || _pdfSharing ? null : _sharePdf,
                    icon: _pdfSharing
                        ? const SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                          )
                        : const Icon(Icons.attach_file, size: 18),
                    label: Text('offer.share_pdf'.tr()),
                    style: FilledButton.styleFrom(
                      backgroundColor: const Color(0xFF25D366),
                    ),
                  ),
                ],
              ),
            ] else if (!_loading && _error != null) ...[
              Align(
                alignment: Alignment.centerRight,
                child: TextButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: Text('common.close'.tr()),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

/// Compact dropdown for selecting a cocktail replacement.
/// Highlighted in tertiary color when the value differs from the original.
class _CocktailDropdown extends StatelessWidget {
  const _CocktailDropdown({
    required this.value,
    required this.allCocktails,
    required this.isChanged,
    required this.onChanged,
  });

  final String value;
  final List<String> allCocktails;
  final bool isChanged;
  final ValueChanged<String?> onChanged;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final effectiveValue = allCocktails.contains(value) ? value : null;

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 2),
      decoration: BoxDecoration(
        color: isChanged
            ? colorScheme.tertiaryContainer
            : colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: isChanged ? colorScheme.tertiary : colorScheme.outline,
          width: isChanged ? 1.5 : 1.0,
        ),
      ),
      child: DropdownButton<String>(
        value: effectiveValue,
        underline: const SizedBox.shrink(),
        isDense: true,
        style: TextStyle(
          fontSize: 13,
          color: isChanged ? colorScheme.onTertiaryContainer : colorScheme.onSurface,
          fontWeight: isChanged ? FontWeight.w600 : FontWeight.normal,
        ),
        items: allCocktails.map((name) {
          return DropdownMenuItem(value: name, child: Text(name));
        }).toList(),
        onChanged: onChanged,
      ),
    );
  }
}
